name: CI/CD Pipeline for STV Voting and Campaign Finance

# Controla quando o workflow será executado
on:
  # Dispara o workflow em push ou pull request apenas para a branch "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Permite executar esse workflow manualmente a partir da aba Actions
  workflow_dispatch:

# Definição dos jobs
jobs:
  build:
    # O tipo de runner que o job será executado
    runs-on: ubuntu-latest

    # Passos que serão executados como parte do job
    steps:
      # Faz o checkout do repositório no $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Instala as dependências do projeto
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Instala as dependências listadas no package.json
      - name: Install Dependencies
        run: npm install

      # Executa os testes unitários com Jest
      - name: Run Unit Tests
        run: npm test

      # Gera relatórios de cobertura de código
      - name: Generate Coverage Report
        run: npm run coverage

      # Executa o provedor Move para validar contratos Move
      - name: Run Move Prover
        run: |
          cd src/contracts
          move-prover CampaignFinance.move

  deploy:
    # O tipo de runner que o job será executado
    runs-on: ubuntu-latest
    needs: build

    # Passos que serão executados como parte do job
    steps:
      # Faz o checkout do repositório no $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      
      # Instala as dependências do projeto
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Sincroniza o financiamento de campanhas
      - name: Sync Campaign Finance
        run: npm run sync-finance

      # Step para realizar o deploy dos contratos Move, se aplicável
      - name: Deploy Move Contracts
        run: |
          cd src/contracts
          move deploy CampaignFinance.move
